services:
#  spring-api:
#    build: .
#    container_name: spring-api
#    env_file: .env
#    ports:
#      - "8080:8080"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
  mysql:
    image: 'mysql:9.6.0'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DB}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASS}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}'
    ports:
      - '${EXTERNAL_MYSQL_PORT:-3306}:3306'
